
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvfmonuesegwebrxyqqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Zm1vbnVlc2Vnd2Vicnh5cXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODc2MzUsImV4cCI6MjA1OTI2MzYzNX0.I2uAkUse18VEE6ZGFyiSnFmzyEDfR-fCTmgCuZoMn18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});
