
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvfmonuesegwebrxyqqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Zm1vbnVlc2Vnd2Vicnh5cXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODc2MzUsImV4cCI6MjA1OTI2MzYzNX0.I2uAkUse18VEE6ZGFyiSnFmzyEDfR-fCTmgCuZoMn18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined
  }
});

// Define a supplementary interface for our invitations table to avoid conflicts with Database type
interface InvitationsTableType {
  id: string;
  code: string;
  email?: string;
  role: "patient" | "nutritionist" | "admin";
  created_by?: string;
  created_at: string;
  expires_at: string;
  used_at?: string;
  used_by?: string;
}

// Add this type to the global scope so it can be used elsewhere
declare global {
  namespace Database {
    interface Tables {
      invitations: {
        Row: InvitationsTableType;
        Insert: Partial<InvitationsTableType> & { code: string; role?: "patient" | "nutritionist" | "admin" };
        Update: Partial<InvitationsTableType>;
      }
    }
    interface Enums {
      patient_goal: "weightLoss" | "weightGain" | "maintenance";
      gender_type: "male" | "female";
      user_role: "patient" | "nutritionist" | "admin";
    }
  }
}
